#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  if [ -d media_build_experimental ]; then
    rm -rf media_build_experimental
  fi

  hg clone http://linuxtv.org/hg/~endriss/media_build_experimental

  cd media_build_experimental
    GIT_REV=`hg id -i`
  cd ..

echo "copying sources..."
  mv media_build_experimental media_build_experimental-$GIT_REV

echo "cleaning sources..."
  rm -rf media_build_experimental-$GIT_REV/.hgignore

echo "packing sources..."
  #tar cvJf media_build_experimental-$GIT_REV.tar.xz media_build_experimental-$GIT_REV
  tar cvJf media_build_experimental.tar.xz media_build_experimental-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf media_build_experimental-$GIT_REV
